# This set of instructions are mandatory, and define the name of the fields
# that the csv files to be inputed should have
# Azimuth and speed are not mandatory fields, so in case they do not exist in the
# source data, they should be given the value of -1 here
# CSVs are expected to have headers
fields:
  ping id: PingID
  vehicle id: VehicleID
  latitude: latitude
  longitude: longitude
  timestamp: timestamp
  azimuth: azimuth   # If no azimuth data, fill with -1
  speed: Speed   # If no speed data, fill with -1

# This is the list of folders where the data will be placed.  They represent the following:
# csv folder --> The place where all the input csv files will be placed. ONLY THOSE CSVs in these folders
# hdf5 folder --> Place where the input files, once converted to hdf5 will be placed
# stops folder --> Place where the hdf5 with all the stops will be placed
# links per route folder --> Place where the hdf5 with all the links likely used by each vehicle will be placed
folders:
  csv folder: D:/GOOGLE_DRIVES/veigacamargo/MapMatchingVehicleGPSData/GPS DATA/
  hdf5 folder: D:/GOOGLE_DRIVES/veigacamargo/MapMatchingVehicleGPSData/OUTPUTS/Data streams in HDF5/
  stops folder: D:/GOOGLE_DRIVES/veigacamargo/MapMatchingVehicleGPSData/OUTPUTS/Vehicle stops/
  links per route folder: D:/GOOGLE_DRIVES/veigacamargo/MapMatchingVehicleGPSData/OUTPUTS/used links/
  map matched folder: D:/GOOGLE_DRIVES/veigacamargo/MapMatchingVehicleGPSData/OUTPUTS/map_matched/
  log folder: D:/GOOGLE_DRIVES/veigacamargo/MapMatchingVehicleGPSData/_logs/
  vehicles folder: D:/GOOGLE_DRIVES/veigacamargo/MapMatchingVehicleGPSData/OUTPUTS/vehicle_stats/
  layer folder: D:/GOOGLE_DRIVES/veigacamargo/MapMatchingVehicleGPSData/NETWORK LAYER/

# Name of the files to be used (both input and output)
file names:
  network file: FAF_network_noded.shp # Input file
  nodes layer: FAF_Nodes.shp # Input file
  aequilibrae graph: network.aeg # OUTPUT file
  all stops: DATA_stops.h5 # OUTPUT file

# Parameters to guide the computational performance
processing:
  cores: 1


geoprocessing:
  buffer size: 0.0006 #Buffer around the links to capture links likely used. Unit is degrees
                      # Each 0.0001 correspond to approximately 11m (36ft) in the radius of the buffer
  azimuth tolerance: 22.5  # In case the network and the GPS data have azimuths, this is the tolerance to be used to
                           # to define if a GPS ping could have used a certain link

  network file fields:
    azimuth: Azimuth # If no Azimuth, put -1
    id: ID
    direction: DIR
    cost: LENGTH
    interpolation: LENGTH

  node file fields:
    id: ID

data quality:
  max speed: 130    # in kmph
  max speed time: 120      # in seconds   --> time that the truck needs to be above the speed limit to be scraped
  minimum pings: 20 # Minimum number of pings that the vehicle needs to have to be considered valid
  minimum coverage: 2 # Minimum diagonal of the Bounding box (km) defined by the GPS pings to be considered a valid vehicle

stops algorithm:
# This key is used to choose the algorithm to be utilized
# 'Delivery stop' or 'Maximum space' 
  algorithm: Maximum space
# Everything else under stops algorithm is a parameter for one of the two algorithms used

# Time in seconds
# Distance in km. Measured as Great circle distance between each consecutive ping
  Maximum space:
    time: 1200
    min distance: 5
    max distance: 20

#This is the algorithm commonly used for ATRI truck GPS data. Initially developed by Pinjari et. Al and improved by
# Pedro Camargo
  Delivery stop:
    stopped speed: 8  # in km/h
    min time stopped: 300 # 5*60 in seconds   --> minimum stopped time to be considered
    max time stopped: 14400 # 4*60*60 in seconds   --> maximum stopped time to be considered
    max stop coverage: 0.8 # in kilometers
